name: Build and Deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  generate-build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false